name: GH-PageDeploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        npm install --save gh-pages
        git config --global user.email "f.yudanto@gmail.com"
        git config --global user.name "fjoeda"
        git remote set-url origin https://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@github.com/fjoeda/fjoeda.github.io.git
        npm run deploy
